# Site settings
title: Chris Borrill
name: Chris Borrill

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/chrisb2
 - title: LinkedIn
   url: https://www.linkedin.com/in/chrisborrill/

#Any buzzword skills you want to include
skills:
 - Java
 - SQL
 - REST
 - Tech Architecture

#Work experience is required
roles:
 - title: Senior Team Lead
   start: 2011
   end: Ongoing
   employer: Orion Health
   description: Orion Health is a global company that develops software to drive efficiency in healthcare and improve healthcare outcomes.
   
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1980
   subject: Chemistry
   school: University of West London

#List of interesting Github repo/projects to include - optional
github:
 - chrisb2/pi_ina219
 - chrisb2/battery-monitor

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
An experienced Technical Leader and Software Designer using the Oracle and Java tool sets, with 16 years experience in 
software development. I am passionate about producing quality designs, documentation and software to meet customer requirements. 
I believe the best software is produced using agile methods.
