# Site settings
title: Chris Borrill
name: Chris Borrill

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/chrisb2
 - title: LinkedIn
   url: https://www.linkedin.com/in/chrisborrill/

#Any buzzword skills you want to include
skills:
 - Java
 - SQL
 - REST
 - Tech Architecture

#Work experience is required
roles:
 - title: Senior Team Lead
   start: 2011
   end: Ongoing
   employer: Orion Health
   description: Orion Health is a global company that develops software to drive efficiency in healthcare and improve healthcare 
   outcomes. I am leading a team of five using scrum to develop health software to improve the delivery of care to patients.
 - title: Software Architect
   start: 2008
   end: 2011
   employer: Arc Innovations
   description: While continuing to lead a scrum team, my role expanded as I worked with the Solution Architects to plan an 
   update of the software services that the company provided, to enable value to be realized from the accumulated meter data.
 - title: Solution Architect
   start: 1998
   end: 2007
   employer: Hewlett Packard
   description: In this role I was responsible for leading the estimation, design and implementation of custom software for HP's clients.
 - title: Project Lead, R&D
   start: 1982
   end: 1997
   employer: Tyco International (was Raychem Ltd)
   description: Led a small team of R&D scientists working on the synthesis of polymers.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1980
   subject: Chemistry
   school: University of West London

#List of interesting Github repo/projects to include - optional
github:
 - chrisb2/pi_ina219
 - chrisb2/battery-monitor

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
